version: "2"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
      - ./.env.secret
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:10.3-alpine"
    restart: always
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - ./.env.secret
    ports:
      - "5433:5432"
