# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180925_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
