# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180925_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
